export const SAVE_DEPUTADOS              = 'SAVE_DEPUTADOS';
export const SAVE_DEPUTADO               = 'SAVE_DEPUTADO';
export const RELOAD_DEPUTADO             = 'RELOAD_DEPUTADO';
export const FILTER_COMISSAO_PARLAMENTAR = 'FILTER_COMISSAO_PARLAMENTAR';
export const SHOW_TODOS_PARLAMENTARES    = 'SHOW_TODOS_PARLAMENTARES';
