export const SAVE_DEPUTADOS              = 'SAVE_DEPUTADOS';
export const SAVE_DEPUTADO               = 'SAVE_DEPUTADO';
export const ORDER_PARLAMENTARES         = 'ORDER_PARLAMENTARES';
export const FILTER_COMISSAO_PARLAMENTAR = 'FILTER_COMISSAO_PARLAMENTAR';
export const SHOW_TODOS_PARLAMENTARES    = 'SHOW_TODOS_PARLAMENTARES';
